### ISSUE TITLE
"Unknown error occurred" Error on the initiial auth login

### ISSUE THREAD

**Issue by myevit** [dahlb/ha_carrier#12]
## System Information

version | core-2023.4.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.84-v8
arch | aarch64
timezone | America/Edmonton
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4983
Installed Version | 1.32.1
Stage | running
Available Repositories | 1261
Downloaded Repositories | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.0
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 28.5 GB
disk_used | 8.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.5.0), AdGuard Home (4.8.5), Matter Server (4.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 4
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 6 April 2023 at 02:29
-- | --
current_recorder_run | 13 April 2023 at 15:52
estimated_db_size | 152.53 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

"Unknown error occurred" Error on the initiial auth login

### Reproduction steps

1. Try to login
2.Error
3.
...

### Debug logs

```text
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/ha_carrier/config_flow.py:95
Integration: Carrier Infinity (documentation, issues)
First occurred: 20:42:01 (1 occurrences)
Last logged: 20:42:01

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/ha_carrier/config_flow.py", line 95, in async_step_user
    await self.hass.async_add_executor_job(api_connection.get_systems)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/carrier_api/api_connection.py", line 101, in get_systems
    System(
  File "/usr/local/lib/python3.10/site-packages/carrier_api/system.py", line 22, in __init__
    self.status = Status(system=self)
  File "/usr/local/lib/python3.10/site-packages/carrier_api/status.py", line 75, in __init__
    self.refresh()
  File "/usr/local/lib/python3.10/site-packages/carrier_api/status.py", line 82, in refresh
    self.mode: str = self.raw_status_json["mode"]
KeyError: 'mode'
```

**Comment by dahlb** [comment]
please add your carrier_api debug logs so we can see what your raw_status_json contains

**Comment by myevit** [comment]
carrier_api debug  is enabled. isn't it the last 3 lines from log I have posted? I can't find anything else related to carrier_api in the log

**Comment by dahlb** [comment]
Sorry, I thought there was logging from the api that was missing.

please try version 1.18.2 with better logging.

What mode is you system current in? and what thermostat model?

**Comment by myevit** [comment]
Thermostat model is SYSTXCCITCO1-B
Updated to 1.18.2

This error originated from a custom integration.

```
Logger: aiohttp.server
Source: custom_components/ha_carrier/config_flow.py:95
Integration: Carrier Infinity (documentation, issues)
First occurred: 12:00:55 (2 occurrences)
Last logged: 12:02:48

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/ha_carrier/config_flow.py", line 95, in async_step_user
    await self.hass.async_add_executor_job(api_connection.get_systems)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/carrier_api/api_connection.py", line 101, in get_systems
    System(
  File "/usr/local/lib/python3.10/site-packages/carrier_api/system.py", line 22, in __init__
    self.status = Status(system=self)
  File "/usr/local/lib/python3.10/site-packages/carrier_api/status.py", line 75, in __init__
    self.refresh()
  File "/usr/local/lib/python3.10/site-packages/carrier_api/status.py", line 83, in refresh
    self.mode: str = self.raw_status_json["mode"]
KeyError: 'mode'

```

**Comment by dahlb** [comment]
@myevit what you provided is only the error logs, please generate and add the debug logging messages from the full home assistant logs

**Comment by myevit** [comment]
here it is (replaced serial numbers with xxxxxxxx):
```
2023-04-14 15:21:47.829 DEBUG (SyncWorker_9) [carrier_api.profile] raw_profile_json:{'$': {'version': '1.48', 'xmlns:atom': 'http://www.w3.org/2005/Atom'}, 'atom:link': [{'$': {'rel': 'self', 'href': 'https://www.app-api.ing.carrier.com/systems/2222W206659/profile'}}, {'$': {'rel': 'http://www.api.ing.carrier.com/rels/system', 'href': 'https://www.app-api.ing.carrier.com/systems/2222W206659'}}], 'timestamp': '2023-04-14T17:21:33.309Z', 'pin': 'xxxxxxxx', 'name': 'Thermostat', 'serial': 'xxxxxxxxx', 'brand': 'Carrier', 'indoorModel': 'xxxxxxxxx', 'indoorSerial': 'xxxxxxxx', 'outdoorModel': '24KBTU', 'outdoorSerial': '-----', 'samType': 'ING', 'firmware': 'CESR131626-04.31', 'model': 'SYSTXCCITC01-B', 'iduversion': 'CESR131671-05   ', 'idutype': 'furnace', 'idusource': 'gas', 'idustages': 'mod', 'iducapacity': 58, 'pwmblower': 'off', 'odutype': 'none', 'oducapacity': 24, 'ventpresent': 'off', 'sampresent': 'off', 'nimpresent': 'off', 'ewtsensorpresent': 'on', 'zoneboards': {'board': [{'$': {'id': '1'}, 'present': 'off'}, {'$': {'id': '2'}, 'present': 'off'}]}, 'zones': {'zone': [{'$': {'id': '1'}, 'present': 'on', 'sensortype': 'ui'}, {'$': {'id': '2'}, 'present': 'off', 'sensortype': 'unknown'}, {'$': {'id': '3'}, 'present': 'off', 'sensortype': 'unknown'}, {'$': {'id': '4'}, 'present': 'off', 'sensortype': 'unknown'}, {'$': {'id': '5'}, 'present': 'off', 'sensortype': 'unknown'}, {'$': {'id': '6'}, 'present': 'off', 'sensortype': 'unknown'}, {'$': {'id': '7'}, 'present': 'off', 'sensortype': 'unknown'}, {'$': {'id': '8'}, 'present': 'off', 'sensortype': 'unknown'}]}}
2023-04-14 15:21:48.183 DEBUG (SyncWorker_9) [carrier_api.status] raw_status_json:{'$': {'version': '1.48', 'xmlns:atom': 'http://www.w3.org/2005/Atom'}, 'atom:link': [{'$': {'rel': 'self', 'href': 'https://www.app-api.ing.carrier.com/systems/xxxxxxx/status'}}, {'$': {'rel': 'http://www.api.ing.carrier.com/rels/system', 'href': 'https://www.app-api.ing.carrier.com/systems/xxxxxxx'}}], 'timestamp': '2023-04-14T18:06:04.745Z', 'pingRate': 15, 'iduStatusPingRate': 93600, 'iduFaultsPingRate': 86400, 'oduStatusPingRate': 90000, 'oduFaultsPingRate': 82800, 'historyPingRate': 75600, 'equipEventsPingRate': 79200, 'rootCausePingRate': 72000, 'serverHasChanges': False, 'configHasChanges': False, 'dealerHasChanges': True, 'dealerLogoHasChanges': False, 'oduConfigHasChanges': False, 'iduConfigHasChanges': False, 'utilityEventsHasChanges': False, 'sensorConfigHasChanges': False, 'sensorProfileHasChanges': False, 'sensorDiagnosticHasChanges': False, 'name': 'Thermostat', 'cfgem': 'C', 'vacatrunning': 'off', 'filtrlvl': 10, 'uvlvl': 0, 'humlvl': 0, 'ventlvl': 2, 'humid': 'off', 'localTime': '2023-04-14T12:06:04.745', 'oprstsmsg': 'idle', 'isDisconnected': False, 'idu': {'cfm': 350, 'opstat': 'off', 'type': 'furnacemodulating'}, 'odu': {'opmode': 'off', 'opstat': 'off', 'type': 'none'}, 'isActive': False, 'zones': {'zone': [{'$': {'id': '1'}, 'name': 'Main Floor', 'enabled': 'on', 'currentActivity': 'home', 'rt': 23, 'rh': 48, 'fan': 'low', 'hold': 'off', 'htsp': 23, 'clsp': 25, 'otmr': None, 'zoneconditioning': 'idle', 'damperposition': 15, 'occupancy': 'unoccupied', 'occupancyOverride': 'off'}, {'$': {'id': '2'}, 'name': 'Zone 2', 'enabled': 'off', 'hold': 'off', 'otmr': None}, {'$': {'id': '3'}, 'name': 'Zone 3', 'enabled': 'off', 'hold': 'off', 'otmr': None}, {'$': {'id': '4'}, 'name': 'Zone 4', 'enabled': 'off', 'hold': 'off', 'otmr': None}, {'$': {'id': '5'}, 'name': 'Zone 5', 'enabled': 'off', 'hold': 'off', 'otmr': None}, {'$': {'id': '6'}, 'name': 'Zone 6', 'enabled': 'off', 'hold': 'off', 'otmr': None}, {'$': {'id': '7'}, 'name': 'Zone 7', 'enabled': 'off', 'hold': 'off', 'otmr': None}, {'$': {'id': '8'}, 'name': 'Zone 8', 'enabled': 'off', 'hold': 'off', 'otmr': None}]}}
```

**Comment by dahlb** [comment]
Thanks those logs are very helpful. Sorry they aren't sanitized, normally we get that information from the device diagnostics in ha which are sanitized but they aren't available until after the initial setup.

Hopefully last question, what is your thermostats current mode?

![Screenshot_20230414-185703.png](https://user-images.githubusercontent.com/54117/232168053-3ae40a6e-d938-411d-963d-8b454f033515.png)

**Comment by PhilDenton** [comment]
For what it's worth, I have the exact same error.  The last few lines at least:

  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/carrier_api/api_connection.py", line 101, in get_systems
    System(
  File "/usr/local/lib/python3.10/site-packages/carrier_api/system.py", line 22, in __init__
    self.status = Status(system=self)
  File "/usr/local/lib/python3.10/site-packages/carrier_api/status.py", line 75, in __init__
    self.refresh()
  File "/usr/local/lib/python3.10/site-packages/carrier_api/status.py", line 83, in refresh
    self.mode: str = self.raw_status_json["mode"]
KeyError: 'mode'

I'm running current HA and ha_carrier app versions but HACS is a little old and I haven't figured out how to pull the debugs above yet.

**Comment by myevit** [comment]
That’s fine, you are spending your time to drive this project, so sanitizing is the secondary thing. Heating is the mode. 
![image](https://user-images.githubusercontent.com/13375246/232176675-35822de1-4216-4ce6-82c2-7651366b4b2e.png)

**Comment by dahlb** [comment]
Thanks for helping me understand this field, seems I was confusing the config mode and status mode field which are not really related and while in some systems status mode is interesting it isn't needed and as of 1.18.3 it is optional. Let me know if you run into any other quirks.

**Comment by myevit** [comment]
Problem solved! Thank you!
![IMG_3032](https://user-images.githubusercontent.com/13375246/232223762-03f61cd2-9399-4d70-a4e0-540a0b004993.png)
