### ISSUE TITLE
503 Server Error

### ISSUE THREAD

**Issue by beckerben** [dahlb/ha_carrier#136]
## System Information

version | core-2024.7.2
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.8.0-39-generic
arch | x86_64
timezone | America/New_York
config_dir | /config

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The integration has stopped working yesterday with the following error:

requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://www.app-api.ing.carrier.com/users/authenticated

Is this isolated to just me or are others seeing it?

### Reproduction steps

1. launch integration

### Debug logs

```text
2024-08-07 02:26:17.697 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/yi_hack/__init__.py", line 123, in init_status
    await mqtt.async_publish(hass, mqtt_conf[CONF_MQTT_PREFIX] + "/cmnd/camera", "", 1, 0)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 147, in async_publish
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Cannot publish to topic 'yicam/cmnd/camera', MQTT is not enabled
2024-08-07 02:26:17.722 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
2024-08-07 02:28:02.981 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 415, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 518, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_carrier/config_flow.py", line 95, in async_step_user
    await self.hass.async_add_executor_job(api_connection.get_systems)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/carrier_api/api_connection.py", line 95, in get_systems
    response_json = self._get(url)
                    ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/carrier_api/api_connection.py", line 42, in _get
    resource_owner_secret=self._get_auth_token(),
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/carrier_api/api_connection.py", line 80, in _get_auth_token
    response = self._post(url, data=creds)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/carrier_api/api_connection.py", line 68, in _post
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://www.app-api.ing.carrier.com/users/authenticated
2024-08-07 02:29:04.915 DEBUG (MainThread) [custom_components.ha_carrier] async setup entry: {'data': {'username': '**REDACTED**', 'password': '**REDACTED**'}, 'disabled_by': None, 'domain': 'ha_carrier', 'entry_id': '01J2RPC3JQYK1DKX65WEZC3C4P', 'minor_version': 1, 'options': {}, 'pref_disable_new_entities': False, 'pref_disable_polling': False, 'source': 'user', 'title': 'beckerben', 'unique_id': None, 'version': 1}
2024-08-07 09:57:41.403 DEBUG (MainThread) [custom_components.ha_carrier] async setup entry: {'data': {'username': '**REDACTED**', 'password': '**REDACTED**'}, 'disabled_by': None, 'domain': 'ha_carrier', 'entry_id': '01J2RPC3JQYK1DKX65WEZC3C4P', 'minor_version': 1, 'options': {}, 'pref_disable_new_entities': False, 'pref_disable_polling': False, 'source': 'user', 'title': 'beckerben', 'unique_id': None, 'version': 1}
2024-08-07 09:57:43.910 DEBUG (MainThread) [custom_components.ha_carrier] async setup entry: {'data': {'username': '**REDACTED**', 'password': '**REDACTED**'}, 'disabled_by': None, 'domain': 'ha_carrier', 'entry_id': '01J2RPC3JQYK1DKX65WEZC3C4P', 'minor_version': 1, 'options': {}, 'pref_disable_new_entities': False, 'pref_disable_polling': False, 'source': 'user', 'title': 'beckerben', 'unique_id': None, 'version': 1}
```

**Comment by ammacdonald3** [comment]
I'm also receiving a 503 error. Couldn't find an API status page for Carrier after a quick Google search, but I'm assuming they're inaccessible right now?

**Comment by beckerben** [comment]
Possibly, I noticed it happen at 22:26 UTC time yesterday but the bryant app on my phone is still working fine so whatever is going on may be isolated to this integration.  Perhaps something in the API changed.

**Comment by timobert** [comment]
I'm having the same issue!

**Comment by tenfiftyseven** [comment]
Same here for the last couple of hours, or at least that is when I noticed it
Carrier says their servers are up and running
Integration??

**Comment by Tirenoth** [comment]
My issues started at 22:13 UTC yesterday.
Looking at my pihole logs, the Carrier app uses completely different APIs than the integration.

App:
sso.carrier.com
realtime.infinity.iot.carrier.com
dataservice.infinity.iot.carrier.com

Integration:
www.app-api.ing.carrier.com

This doesn't help narrow down outage vs API changes, but it at least explains why the official app is still working.

**Comment by beckerben** [comment]
Digging a little deeper seems to be the same issue from the [sister project](https://github.com/grivkees/homebridge-carrier-infinity/issues/527) and definitely an API issue.

**Comment by mbspears** [comment]
Same issue here - hopeful that a solution will be available soon.

**Comment by FiveElementNinja** [comment]
I was having the same problem, but mine just started working again.

**Comment by dahlb** [comment]
This has happened a few times now, carrier does show maintenance and has downtime typically less then 24 hours
