### ISSUE TITLE
Authenticate

### ISSUE THREAD

**Issue by michelcs77** [dahlb/ha_carrier#27]
### System Health details

Downloaded the integration, an unknown error message when logging in.

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Setup logging to debug and i don't now what i'am doing wrong?

### Reproduction steps

1. Just installed from HACS
2. Add integration
3. Login with my carrier credentials
...

### Debug logs

```text
Logger: aiohttp.server
Source: custom_components/ha_carrier/config_flow.py:95
Integration: Carrier Infinity ([documentation](https://github.com/dahlb/ha_carrier), [issues](https://github.com/dahlb/ha_carrier/issues))
First occurred: 9:22:40 PM (1 occurrences)
Last logged: 9:22:40 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/ha_carrier/config_flow.py", line 95, in async_step_user
    await self.hass.async_add_executor_job(api_connection.get_systems)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/carrier_api/api_connection.py", line 95, in get_systems
    response_json = self._get(url)
  File "/usr/local/lib/python3.10/site-packages/carrier_api/api_connection.py", line 42, in _get
    resource_owner_secret=self._get_auth_token(),
  File "/usr/local/lib/python3.10/site-packages/carrier_api/api_connection.py", line 84, in _get_auth_token
    raise AuthError(response_json["error"]["message"])
carrier_api.errors.AuthError: NotFound
```

### Diagnostics dump

......

**Comment by dahlb** [comment]
I think that error means your username is unrecognized, does it work when you login to https://play.google.com/store/apps/details?id=com.myinfinity

**Comment by michelcs77** [comment]
Hi,
Thanx, for the feedback. I now whats wrong i dit used de wrong integration.
