### ISSUE TITLE
No Authorization - API Error

### ISSUE THREAD

**Issue by balsman225** [dahlb/ha_carrier#5]
Integration was working for a few days but It has stopped.
When trying to remove and re-add I get "Unknown error occurred" from Home assistant.

Looking over the logs and the API url It shows as No Authorization
I am able to login to the myinfinitytouch web portal and app so I know my creds are correct.

Thank you - 

Logger: aiohttp.server
Source: custom_components/ha_carrier/config_flow.py:85 
Integration: Carrier Infinity ([documentation](https://github.com/dahlb/ha_carrier), [issues](https://github.com/dahlb/ha_carrier/issues)) 
First occurred: 9:36:57 PM (3 occurrences) 
Last logged: 9:40:46 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 145, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 253, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/ha_carrier/config_flow.py", line 85, in async_step_user
    await self.hass.async_add_executor_job(api_connection.get_systems)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/carrier_api/api_connection.py", line 94, in get_systems
    System(
  File "/usr/local/lib/python3.10/site-packages/carrier_api/system.py", line 22, in __init__
    self.status = Status(system=self)
  File "/usr/local/lib/python3.10/site-packages/carrier_api/status.py", line 69, in __init__
    self.refresh()
  File "/usr/local/lib/python3.10/site-packages/carrier_api/status.py", line 72, in refresh
    self.raw_status_json = self.system.api_connection.get_status(
  File "/usr/local/lib/python3.10/site-packages/carrier_api/api_connection.py", line 108, in get_status
    return self._get(url)["status"]
  File "/usr/local/lib/python3.10/site-packages/carrier_api/api_connection.py", line 46, in _get
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://www.app-api.ing.carrier.com/systems/3019W102625/statu

**Comment by dahlb** [comment]
It was down for me too, guessing if you reload the integration it'll be back up for you too.  Seems to be often maintenance windows as I've only had it in the evenings. Though if I find a fix or more insight I'll add here

**Comment by dahlb** [comment]
you can see the same 500 errors when using the carrier official site at https://www.myinfinitytouch.carrier.com/login the mobile app heavily uses caching but I don't think it works while their api is down either

**Comment by balsman225** [comment]
> It was down for me too, guessing if you reload the integration it'll be back up for you too. Seems to be often maintenance windows as I've only had it in the evenings. Though if I find a fix or more insight I'll add here

Thanks for the info, I’ll give it a shot during the day to see if it’s just evening maintenances. I can login without issue to the site just not the HASS integration.

**Comment by dahlb** [comment]
I could login to the carrier site but if you check the API calls the site uses the site makes a request for system status that was returning 500 and just was hiding the network errors

**Comment by balsman225** [comment]
> I could login to the carrier site but if you check the API calls the site uses the site makes a request for system status that was returning 500 and just was hiding the network errors

Thanks again for the reply. I appreciate the info and explanation. I’ll just hold tight for them to work out their API. You can close this issue if you’d like since it’s on their side and not your integration. I just wanted to open it incase it was a simple fix.
