### ISSUE TITLE
1.21.3 fails after updating

### ISSUE THREAD

**Issue by adamsd5** [dahlb/ha_carrier#91]
### System Health details

I don't know how to get this.

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Sorry for the lack of details.  After updating to 1.21.3 today, the software was complaining of a configuration error.  Sadly, I was unable to find the configuration file or understand what it was complaining about.  I had to restore a full backup and will skip this update.  Happy to have you reach out for questions.

### Reproduction steps

1. Update to 1.21.3
2. Restart
3.
...

### Debug logs

```text
Don't have it
```

### Diagnostics dump

Not sending it

**Comment by dahlb** [comment]
assuming this is the missing log version 1.21.3 requires ha version 2024.2.0 or newer

```
Logger: homeassistant.loader
Source: loader.py:838
First occurred: 4:37:32 AM (1 occurrences)
Last logged: 4:37:32 AM

Unexpected exception importing platform custom_components.ha_carrier.climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 838, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 855, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/ha_carrier/climate.py", line 53, in <module>
    ClimateEntityFeature.TURN_ON
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: TURN_ON
```
